export const chapter7=Object.freeze({chapter:7,title:'TEAM CAPTAIN',source:'APPROVED_STORYLINE.md#CHAPTER-7',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 7','TEAM','CAPTAIN','','Encourage teammates.','Notice teammates. Use words that help.','Build up your team.','CORE RULE','Notice your teammates.','Encourage their courage and effort.','Make your team better.','NOTICE • ENCOURAGE • LEAD'],
['CHAPTER 7','THE STORY — PART 1','NOTICE THE DUGOUT','Gio has spent a lot of time learning how to manage','his own at-bats. Now Coach Mark asks him','to notice something else: the dugout.','','One teammate strikes out and sits alone.','Another makes an error and looks at the ground.','A younger player looks nervous about a hard pitcher.','','Gio recognizes those feelings.','He has felt all of them himself.','','Coach Mark tells Gio, “Brave Hitters don’t only make','themselves better. They make the people around them better.”','','Gio looks around and decides to help.','TEAM','FIRST.','!','LEADERS NOTICE THEIR TEAMMATES.','ENCOURAGEMENT HELPS PLAYERS RESET.','NOTICE THE TEAM.','BUILD THEM UP'],
['CHAPTER 7','THE STORY — PART 2','WORDS THAT HELP','Gio begins using what he has learned','to encourage his teammates.','','After a strikeout: “Next pitch.','You’ve got another one.”','Before an at-bat: “See it early. Trust your swing.”','After a hard-hit out: “That was a great swing.”','','Something changes. Gio stops thinking only','about his own performance. He helps create','a dugout where players feel supported','enough to compete bravely.','','Helping teammates makes Gio feel more confident too.','MAKE THE PEOPLE AROUND YOU BETTER.','A few useful words can help a teammate reset and compete.','BUILD UP YOUR TEAM.','BRAVE HITTERS MAKE TEAMMATES BETTER'],
['CHAPTER 7','WHAT GIO LEARNED','TEAM LEADERSHIP','1  LEADERS NOTICE OTHERS','Leadership starts with','paying attention to teammates,','not only yourself.','2  WORDS MATTER','A few encouraging words','at the right moment can help','a teammate reset and compete.','3  CELEBRATE THE RIGHT THINGS','Praise courage, effort,','good decisions, hard contact,','and recovery—not only results.','WHY IT MATTERS','Baseball is a team sport. A positive dugout helps players','recover from mistakes and play with greater confidence.','Leadership is something Gio can practice regardless','of position, batting average, or age.','REAL BASEBALL EXAMPLE','Strong teams stay engaged even when they are not batting','or making the play. Leadership can look like encouragement,','energy, attention, preparation, or helping','a teammate recover.','','COACH MARK SAYS','Make the people','around you better.','BRAVE HITTERS BUILD UP THEIR TEAM.','LEADERSHIP'],
['CHAPTER 7','PARENT DUGOUT','PRAISE TEAM LEADERSHIP','Ask about teammates as well as personal performance.','PRAISE','✓ Encouraging a teammate','✓ Celebrating someone else','✓ Helping a player reset','✓ Staying engaged in the dugout','✓ Unselfish team behavior','ASK','“Who did you encourage today?”','','“Who had a great moment?”','','','“How did you help your team?”','AVOID','Making leadership depend','on being the best player.','','','Every player can notice,','encourage, and support','the people around them.','','PARENT REMINDER','Ask, “Did someone need you today?”','Praise the moments your player chose the team.','HELP YOUR PLAYER PRACTICE UNSELFISH LEADERSHIP.','LEADERSHIP'],
['CHAPTER 7','REFLECTION TIME','THINK. WRITE. GROW.','Notice teammates and use words that help them compete.','1. Who did you encourage?','2. When did a teammate need support?','3. What words helped?','4. How does encouragement make you feel?','5. What kind of teammate do you want to be?','REMEMBER','Notice your teammates.','Encourage courage and effort.','Build up your team.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','LEADERSHIP'],
['CHAPTER 7','KEY TAKEAWAYS','REMEMBER THIS','1','NOTICE YOUR TEAMMATES.','2','ENCOURAGE THEM.','3','CELEBRATE THEIR SUCCESS.','4','HELP THEM RESET.','5','BUILD UP YOUR TEAM.','USE YOUR WORDS, ENERGY, AND ATTENTION','TO MAKE THE PEOPLE AROUND YOU BETTER.','LEAD THE DUGOUT.','LEADERSHIP']
]});
