import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGE, FONT } from '../system/production-config.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../..');
const out = path.join(root, 'production/pages/weekly-missions/source');
fs.mkdirSync(out, { recursive: true });

const assetPaths = { crest:'assets/brand/crest.png', gio:'assets/gio/gio_celebrate.png', coach:'assets/coach-mark/coach_mark_canonical.png', halftone:'assets/decorations/halftone.png', dirt:'assets/decorations/dirt.png', redbrush:'assets/decorations/redbrush.png', burst:'assets/decorations/burst.png' };
const data = Object.fromEntries(Object.entries(assetPaths).map(([k,v]) => [k, `data:image/png;base64,${fs.readFileSync(path.join(root,v)).toString('base64')}`]));
const esc = v => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const text = (v,x,y,size=48,o={}) => `<text x="${x}" y="${y}" class="${o.display?'display':'body'}" font-size="${size}" font-weight="${o.weight||(o.display?700:600)}" fill="${o.fill||'#171513'}"${o.anchor?` text-anchor="${o.anchor}"`:''}${o.italic?' font-style="italic"':''}>${esc(v)}</text>`;
const lines = (a,x,y,size=48,step=66,o={}) => a.map((v,i)=>text(v,x,y+i*step,size,o)).join('');
const img = (k,x,y,w,h,opacity=1) => `<image href="${data[k]}" x="${x}" y="${y}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet" opacity="${opacity}"/>`;
const wrap = (value,max=43) => { const words=value.split(/\s+/), out=[]; let line=''; for(const word of words){ const next=line?`${line} ${word}`:word; if(next.length>max&&line){out.push(line);line=word;}else line=next;} if(line)out.push(line); return out; };
const footer = `<path d="M0 2380 Q900 2315 1660 2385 T3300 2360V2550H0z" fill="#111"/><path d="M2550 2380h750v170H2455z" fill="#c9151e"/><circle cx="105" cy="2463" r="53" fill="none" stroke="#ef2530" stroke-width="15"/><path d="M105 2420l13 27 30 4-22 21 5 30-26-14-27 14 6-30-22-21 30-4z" fill="#ef2530"/>${text('BRAVE HITTER ACADEMY',190,2485,45,{display:true,fill:'#fff'})}`;
const base = (page,title,week='') => `<svg xmlns="http://www.w3.org/2000/svg" width="3300" height="2550" viewBox="0 0 3300 2550"><metadata>section:weekly-missions;page:${page};source:WEEKLY_MISSIONS.md#${page===1?'PAGE-1':`WEEK-${week}`}</metadata><defs><filter id="grain"><feTurbulence baseFrequency=".75" numOctaves="2" seed="41" type="fractalNoise"/><feColorMatrix values="0 0 0 0 .35 0 0 0 0 .3 0 0 0 0 .24 0 0 0 .05 0"/></filter></defs><style>.display{font-family:'Oswald';font-weight:700;letter-spacing:2px}.body{font-family:'Source Sans 3'}</style><rect width="3300" height="2550" fill="#f5eedf"/><rect width="3300" height="2550" filter="url(#grain)" opacity=".55"/><path d="M0 0h3300v200H0z" fill="#111"/><path d="M0 0h760l115 100-115 100H0z" fill="#c9151e"/>${img('crest',42,24,150,150)}${text('WEEKLY MISSIONS',225,133,68,{display:true,fill:'#fff'})}${week?text(`WEEK ${week}`,1030,132,58,{display:true,fill:'#f3b21a'}):''}${title?text(title,3180,132,title.length>25?48:58,{display:true,fill:'#fff',anchor:'end'}):''}${footer}`;
const missions = [
['TAKE YOUR SWING','Choose courage instead of hesitation.',['Decide before the pitch: “If it\'s mine, I\'m swinging.”','Take committed swings at hittable pitches.','Give yourself credit for Brave Swings—even when you miss.'],'When did you take a swing you were proud of?'],
['CONTROL WHAT YOU CAN','Put your energy into choices, not outcomes.',['Focus on preparation, effort and attitude.','After each at-bat, name one thing you controlled well.','Replace “I need a hit” with “I need a good decision.”'],'What did you control well this week?'],
['OWN YOUR ATTITUDE','Be your own positive coach.',['Catch one negative thought each day.','Replace it with a useful baseball thought.','Use strong body language after mistakes.'],'What positive phrase helped you most?'],
['RESET FAST','Win the next pitch.',['After a mistake, take one slow breath.','Learn one thing—then let the mistake go.','Say “Next pitch” and return to ready.'],'How quickly did you recover from a tough moment?'],
['PREPARE LIKE A PRO','Build confidence before game day.',['Arrive ready with your gear and plan.','Use visualization before practice or games.','Choose one simple focus for the day.'],'What preparation made you feel most ready?'],
['PLAY WITH CONFIDENCE','Let your preparation show.',['Use your pre-at-bat routine.','Stand tall and breathe slowly.','Trust your swing instead of trying to control every movement.'],'When did you play free this week?'],
['FINISH STRONG','Compete through the final pitch.',['Keep your energy up late in practices and games.','Run hard even when you\'re frustrated.','Treat your final rep like your first.'],'Where did you show extra effort at the end?'],
['BE A GREAT TEAMMATE','Make somebody else better.',['Encourage a teammate after a mistake.','Celebrate someone else\'s success.','Help the team without being asked.'],'Who did you help this week, and how?'],
['STAY POSITIVE','Look for evidence that you\'re growing.',['Write down three wins after baseball.','Notice good decisions—not only hits.','Speak to yourself like you would a teammate.'],'What win would you have missed if you only looked at the score?'],
['DO HARD THINGS','Practice courage on purpose.',['Choose one drill or situation that challenges you.','Stay engaged when you struggle.','Do one brave baseball thing each day.'],'What hard thing are you proud you tried?'],
['GET 1% BETTER','Small improvements add up.',['Pick one skill to improve this week.','Measure effort or repetitions instead of perfection.','At week\'s end, name one thing that feels easier.'],'Where did you improve—even a little?'],
['BE THE BRAVE HITTER','Put the whole Academy together.',['Prepare with purpose.','Compete with courage and take your swing.','Reset, encourage teammates, and keep growing.'],'What makes you a Brave Hitter now?']
];

const pages=[];
pages[1]=base(1,'HOW IT WORKS')+`<path d="M0 200h1420l-210 2180H0z" fill="#111"/>${img('halftone',0,200,1450,2180,.13)}${img('burst',130,520,1050,1050,.16)}${img('gio',260,520,820,1330)}${text('12 WEEKS',1550,510,118,{display:true,fill:'#c9151e'})}${text('12 SKILLS',1550,650,118,{display:true})}${text('ONE BRAVER HITTER',1550,790,100,{display:true,fill:'#c9151e'})}${lines(['Each week, practice one mental skill from the Academy.','Complete the three challenges, mark the days you practiced,','and answer the reflection question.'],1550,1030,55,82)}<rect x="1510" y="1320" width="1600" height="500" rx="38" fill="#c9151e"/>${text('THE GOAL IS REPETITION.',1590,1460,72,{display:true,fill:'#fff'})}${lines(['Do not chase a perfect week. Make one small','Brave Hitter choice at a time.'],1590,1585,58,82,{fill:'#fff'})}${text('SHOW UP. PRACTICE. GROW.',2310,2050,72,{display:true,fill:'#111',anchor:'middle'})}</svg>`;
for(let i=0;i<missions.length;i++){
  const [title,mission,challenges,reflection]=missions[i], week=i+1;
  const challengeMarkup=challenges.map((c,j)=>{const y=875+j*270, ls=wrap(c,38); return `<circle cx="220" cy="${y-20}" r="54" fill="${j===1?'#111':'#c9151e'}"/>${text(j+1,220,y,52,{display:true,fill:'#fff',anchor:'middle'})}${lines(ls,310,y-15,58,72)}`;}).join('');
  const days=['MON','TUE','WED','THU','FRI','SAT','SUN'];
  const tracker=days.map((d,j)=>{const x=1840+j*175; return `${text(d,x,1165,40,{display:true,anchor:'middle'})}<circle cx="${x}" cy="1245" r="43" fill="#fffaf0" stroke="#c9151e" stroke-width="8"/>`;}).join('');
  pages[week+1]=base(week+1,'',week)+`<rect x="120" y="300" width="3060" height="205" rx="28" fill="#c9151e"/>${text('THIS WEEK’S MISSION',185,385,50,{display:true,fill:'#f3b21a'})}${text(title,185,470,title.length>25?66:74,{display:true,fill:'#fff'})}<rect x="120" y="570" width="1500" height="1120" rx="34" fill="#fffaf0" stroke="#111" stroke-width="10"/>${text('THREE CHALLENGES',185,680,68,{display:true,fill:'#c9151e'})}${challengeMarkup}<rect x="1700" y="570" width="1480" height="770" rx="34" fill="#fffaf0" stroke="#c9151e" stroke-width="10"/>${text('MONDAY–SUNDAY TRACKER',1770,680,66,{display:true})}${text('MARK EACH DAY YOU PRACTICE',1770,760,44,{fill:'#6a625a'})}${tracker}<rect x="1700" y="1390" width="1480" height="300" rx="34" fill="#111"/>${text('DAYS COMPLETED',1770,1510,60,{display:true,fill:'#f3b21a'})}${text('____ / 7',2900,1590,96,{display:true,fill:'#fff',anchor:'end'})}<rect x="120" y="1760" width="1970" height="470" rx="34" fill="#fffaf0" stroke="#c9151e" stroke-width="10"/>${text('REFLECTION',185,1870,64,{display:true,fill:'#c9151e'})}${lines(wrap(reflection,52),185,1970,52,68)}<line x1="185" y1="2140" x2="2015" y2="2140" stroke="#272322" stroke-width="5"/><rect x="2160" y="1760" width="1020" height="470" rx="34" fill="#c9151e"/>${img('coach',2180,1770,360,420)}${text('COACH MARK SAYS',2550,1885,52,{display:true,fill:'#f3b21a'})}${lines(wrap(mission,24),2550,1980,48,62,{fill:'#fff'})}</svg>`;
}
for(let i=1;i<=13;i++) fs.writeFileSync(path.join(out,`weekly_missions_page_${String(i).padStart(2,'0')}.svg`),pages[i]);
fs.writeFileSync(path.join(out,'build-manifest.json'),JSON.stringify({section:'Weekly Missions',source:'WEEKLY_MISSIONS.md',pageCount:13,pagePx:[PAGE.widthPx,PAGE.heightPx],pagePt:[PAGE.widthPt,PAGE.heightPt],assets:assetPaths,fonts:FONT},null,2)+'\n');
console.log(`Wrote 13 Weekly Missions SVG pages to ${out}`);
