// Copy is drawn from APPROVED_STORYLINE.md, Chapter 10; line breaks fit frozen slots.
export const chapter10=Object.freeze({chapter:10,title:'BOUNCE BACK CHAMPION',source:'APPROVED_STORYLINE.md#CHAPTER-10',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 10','BOUNCE','BACK','CHAMPION','Measure recovery, not perfection.','Mistakes are part of baseball.','Getting ready again is a skill.','CORE RULE','Breathe. Learn one thing.','Reset your body.','Find the next job.','RESET • RELOAD • GO AGAIN'],
['CHAPTER 10','THE STORY — PART 1','THE ERROR LINGERS','Gio makes an error. The baseball rolls past him.','A runner advances.','','“I can’t believe I did that,” he thinks.','He wants the play back. But baseball does not rewind.','','A few pitches later, another ball comes toward Gio.','He is still thinking about the error.','He reacts late.','','Coach Mark later explains that everyone talks','about avoiding mistakes.','','But mistakes are guaranteed in baseball.','The real skill is recovery.','GET BACK','TO READY.','!','MISTAKES ARE PART OF BASEBALL.','RECOVERY IS A SKILL YOU CAN PRACTICE.','THE NEXT PLAY NEEDS YOUR ATTENTION.','RECOVERY'],
['CHAPTER 10','THE STORY — PART 2','BACK TO READY','Instead of “Did I make a mistake?”','Coach Mark teaches Gio to ask:','“How quickly did I get back?”','','Gio develops a simple bounce-back process.','Breathe. Learn one thing.','Reset his body. Find the next job.','','Later, Gio makes another mistake.','He is disappointed—but this time he takes a breath.','','“Next play.” He gets ready.','The mistake lasts one play instead of becoming three.','That is progress.','HOW QUICKLY DID I GET BACK?','Measure recovery, not perfection.','RESET. RELOAD. GO AGAIN.','RECOVERY'],
['CHAPTER 10','WHAT GIO LEARNED','RECOVERY IS A SKILL','1  MISTAKES ARE GUARANTEED','Every player makes errors,','strikes out, takes bad swings,','or makes poor decisions.','2  RECOVERY IS A SKILL','Gio can practice getting ready','again instead of waiting for','frustration to disappear.','3  DON’T TURN ONE INTO TWO','The goal is not perfection.','Do not let one mistake steal','the next opportunity.','WHY IT MATTERS','Fear of mistakes can make players cautious.','When Gio trusts his ability to recover, he can','compete more freely. A mistake does not have','to control what happens next.','REAL BASEBALL EXAMPLE','Every player makes errors. A player’s response','after an error can influence far more baseball','than the original mistake.','Recovery speed is trainable.','','COACH MARK SAYS','How quickly','did I get back?','BRAVE HITTERS PRACTICE GETTING READY AGAIN.','RECOVERY'],
['CHAPTER 10','PARENT DUGOUT','CELEBRATE RECOVERY','Notice how quickly your player gets ready again.','PRAISE','✓ Taking a breath','✓ Learning one thing','✓ Resetting the body','✓ Finding the next job','✓ Getting ready again','SAY','“I loved how quickly','you got ready for','the next play.”','','Notice the','recovery too.','AVOID','Focusing only on:','“You made an error.”','','Help your player see','recovery as a skill','worth celebrating.','','','PARENT REMINDER','Measure the recovery too—not only the mistake.','Getting ready for the next play is worth celebrating.','MEASURE RECOVERY, NOT PERFECTION.','RECOVERY'],
['CHAPTER 10','REFLECTION TIME','THINK. WRITE. GROW.','Notice how you returned to ready after a mistake.','1. What mistake was difficult today?','2. How long did it stay with you?','3. What helped you reset?','4. What was your next job?','5. How could you recover even faster next time?','REMEMBER','Breathe. Learn.','Reset your body.','Find the next job.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','RECOVERY'],
['CHAPTER 10','KEY TAKEAWAYS','REMEMBER THIS','1','MISTAKES WILL HAPPEN.','2','BREATHE.','3','LEARN ONE THING.','4','FIND THE NEXT JOB.','5','RESET. RELOAD. GO AGAIN.','MEASURE RECOVERY, NOT PERFECTION.','DO NOT LET ONE MISTAKE STEAL THE NEXT PLAY.','GET BACK TO READY.','RECOVERY']
]});
