export const chapter3=Object.freeze({chapter:3,title:'FAST PITCH MONSTER',source:'APPROVED_STORYLINE.md#CHAPTER-3',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 3','FAST','PITCH','MONSTER','See the ball early.','You cannot control how fast they throw.','You can control how well you see it.','CORE RULE','Get ready early.','Find the release point.','Track the ball.','EARLY EYES • CALM MIND • TRUSTED TIMING'],
['CHAPTER 3','THE STORY — PART 1','THE FAST PITCH MONSTER','Gio faces a pitcher throwing harder than anyone he has seen.','The first fastball explodes into the catcher’s glove. POP!','','In Gio’s imagination, the pitcher becomes a monster.','His thoughts race: “He’s too fast. I can’t catch up.”','','The next pitch feels faster because Gio expects to be late.','Coach Mark notices and asks, “When are you seeing the ball?”','','Gio is not sure. Coach Mark explains that Gio does not','need to become magically faster. He needs more time.','That starts with seeing the baseball as early as possible.','','Get ready early. Watch the pitcher. Find the release point.','Early eyes can make a fast pitch feel less surprising.','EARLY','EYES.','!','YOU DO NOT HAVE TO MAKE THE PITCHER SLOWER.','GIVE YOURSELF MORE TIME TO SEE IT.','FIND THE BALL EARLY.','SEE THE BALL EARLY'],
['CHAPTER 3','THE STORY — PART 2','EARLY EYES','Coach Mark gives Gio a plan: get ready early.','Watch the pitcher. Find the release point. Track the ball.','','At his next at-bat, Gio stops thinking, “He’s too fast.”','Instead he tells himself, “Early eyes.”','The pitcher throws. Gio picks up the baseball sooner.','','The pitch has not slowed down, but it is less surprising.','Another pitch comes. Gio sees it early and tracks it.','He trusts his timing and takes his swing.','','The Fast Pitch Monster does not look quite so monstrous.','Gio cannot control velocity, but he can control his eyes.','Preparation and attention give him time to make a decision.','“EARLY EYES.”','Seeing the ball sooner makes fast pitching feel manageable.','SEE IT EARLY.','FIND IT, TRACK IT, TRUST YOUR TIMING'],
['CHAPTER 3','WHAT GIO LEARNED','SEE THE BALL EARLY','1  PICK IT UP EARLY','The sooner Gio sees the ball,','the more information his brain','has about the pitch.','2  TRACK THE BALL','The release is only the start.','Keep attention on the baseball','as it travels toward the plate.','3  TRUST YOUR TIMING','See the pitch, recognize what','you can hit, and trust your','preparation instead of panicking.','WHY IT MATTERS','Faster pitching can make hitters feel rushed. Seeing the','ball earlier helps Gio feel less surprised and gives him','a better chance to recognize the pitch and make a calm,','confident decision.','REAL BASEBALL EXAMPLE','Hitters facing better pitching do not make the pitcher','slower. They improve preparation, visual attention, timing,','and decision-making. Picking up the baseball earlier gives','the hitter more useful information.','','COACH MARK SAYS','Early eyes.','Trust your timing.','BRAVE HITTERS SEE THE BALL EARLY.','SEE THE BALL EARLY'],
['CHAPTER 3','PARENT DUGOUT','FOCUS ON A USEFUL ACTION','Help your player prepare instead of magnifying the threat.','PRAISE','✓ Getting ready early','✓ Finding the release point','✓ Tracking the baseball','✓ Trusting prepared timing','✓ Staying calm against speed','ASK','“When did you see the ball?”','','“Where was the pitcher’s','release point?”','','“What helped you feel ready?”','AVOID','Repeatedly talking about','how hard the pitcher throws.','','That can make velocity feel','like a threat instead of a','challenge Gio can prepare for.','','','PARENT REMINDER','Use short cues: “Get ready early.” “Find the ball.”','“Early eyes.” “Trust your timing.”','FOCUS ON WHAT YOUR PLAYER CAN DO.','SEE THE BALL EARLY'],
['CHAPTER 3','REFLECTION TIME','THINK. WRITE. GROW.','Notice how preparation and early eyes changed the at-bat.','1. What does fast pitching make you think about?','2. Where can you look to see the ball earlier?','3. What phrase helps you stay focused?','4. Did a fast pitch feel easier once you saw it early?','5. What can you control against a hard thrower?','REMEMBER','Get ready early. Find','the release point. Track','the ball and trust your timing.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','SEE THE BALL EARLY'],
['CHAPTER 3','KEY TAKEAWAYS','REMEMBER THIS','1','GET READY EARLY.','2','FIND THE RELEASE POINT.','3','TRACK THE BALL.','4','TRUST YOUR TIMING.','5','SEE IT EARLY. OWN IT.','YOU CANNOT CONTROL THE PITCHER’S SPEED.','YOU CAN CONTROL HOW WELL YOU SEE IT.','EARLY EYES CREATE MORE TIME.','SEE THE BALL EARLY']
]});
