// Copy is drawn from APPROVED_STORYLINE.md, Chapter 12; line breaks fit frozen slots.
export const chapter12=Object.freeze({chapter:12,title:'ALL-STAR MINDSET',source:'APPROVED_STORYLINE.md#CHAPTER-12',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 12','ALL-STAR','MINDSET','','Confidence is a choice.','Repeated brave action strengthens it.','Use every tool you have built.','CORE RULE','Choose courage.','Trust yourself.','Keep competing.','BE BRAVE. TRUST YOURSELF. PLAY FREE.'],
['CHAPTER 12','THE STORY — PART 1','LOOK HOW FAR YOU’VE COME','Gio looks back at the player he was','when he first entered Brave Hitter Academy.','He remembers being afraid to swing.','','He remembers the Fast Pitch Monster.','Strikeouts that followed him to the dugout.','Negative thoughts. Pressure. Mistakes.','','Those things have not disappeared completely.','Gio still gets nervous sometimes.','He still misses pitches and strikes out.','He still makes mistakes.','','But Gio is different now.','He knows what to do when those moments happen.','CHOOSE','CONFIDENCE.','!','CONFIDENCE GROWS THROUGH ACTION.','BRAVE DECISIONS BUILD IT.','KEEP COMPETING.','ALL-STAR'],
['CHAPTER 12','THE STORY — PART 2','THE ALL-STAR MINDSET','Be brave. Take his swing. See the ball early.','Say “Next pitch.” Hunt hard contact. Coach himself positively.','Build up teammates. Welcome big moments. Bounce back.','','Trust his training.','','Coach Mark calls this the All-Star Mindset.','It is not “I will always succeed.”','It is “Whatever happens, I know how to compete.”','','Confidence is not something Gio has to wait for.','Every brave decision, reset, committed swing, and moment','of trust casts a vote. Gio steps toward the field—','still growing, and knowing how to be a Brave Hitter.','CHOOSE CONFIDENCE.','One brave action at a time.','BE BRAVE. TRUST YOURSELF. PLAY FREE.','ALL-STAR'],
['CHAPTER 12','WHAT GIO LEARNED','ALL-STAR MINDSET','1  CONFIDENCE IS BUILT','It grows through brave actions,','preparation, recovery, and trust.','','2  CONFIDENCE NEEDS NO CERTAINTY','Gio does not need to know','he will get a hit. He can handle','the moment and compete.','3 USE YOUR TOOLS · 4 CHOOSE HOW TO COMPETE','Academy lessons give Gio a toolbox.','He can choose courage, focus, effort,','attitude, and response.','WHY IT MATTERS','If confidence depends on always playing well, it disappears','when baseball becomes difficult. Gio now has durable confidence','built around how he prepares, thinks, responds, and competes.','','REAL BASEBALL EXAMPLE','Confident competitors do not expect perfection.','They build routines, reset skills, useful self-talk,','preparation habits, and ways to respond to adversity.','Those tools help confidence survive difficult games.','','COACH MARK SAYS','Whatever happens,','you know how to compete.','BE BRAVE. TRUST YOURSELF. PLAY FREE.','ALL-STAR'],
['CHAPTER 12','PARENT DUGOUT','CELEBRATE THE GROWTH','Help your player recognize growth that is not visible in statistics.','PRAISE','✓ Brave decisions','✓ Better responses','✓ Useful self-talk','✓ Being a teammate','✓ Trusting the work','SAY','“What feels easier now?”','“How do you handle mistakes differently?”','“What do you know now when you’re nervous?”','“What makes you a Brave Hitter?”','','','AVOID','Measuring growth only','by baseball results.','','Celebrate the person','and competitor being','developed—not merely','the performance.','','PARENT REMINDER','Compare your player to the player who began the Academy.','Notice courage, focus, response, leadership, and trust.','CONFIDENCE IS A CHOICE.','ALL-STAR'],
['CHAPTER 12','REFLECTION TIME','THINK. WRITE. GROW.','Look back at the Brave Hitter you have become.','1. How are you different from when you started?','2. Which Brave Hitter skill helps you most?','3. What are you most proud of?','4. What will you do the next time confidence drops?','5. What kind of teammate have you become?','6. What does being a Brave Hitter','mean to you?','________________________','________________________','BRAVE HITTERS KEEP CHOOSING CONFIDENCE.','ALL-STAR'],
['CHAPTER 12','KEY TAKEAWAYS','REMEMBER THIS','1','BE BRAVE WHEN YOU’RE NERVOUS.','2','TAKE YOUR SWING. SEE THE BALL.','3','TRUST YOUR WORK. BOUNCE BACK.','4','BUILD UP THE PLAYERS AROUND YOU.','5','YOU DON’T HAVE TO BE PERFECT TO BE CONFIDENT.','KEEP CHOOSING TO COMPETE. HAVE FUN.','BE BRAVE. TRUST YOURSELF. PLAY FREE.','YOU KNOW HOW TO COMPETE.','ALL-STAR']
]});
