export const chapter8=Object.freeze({chapter:8,title:'BRAVE SWING CHALLENGE',source:'APPROVED_STORYLINE.md#CHAPTER-8',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 8','BRAVE','SWING','CHALLENGE','10 Brave Swings.','Recognize your pitch. Commit completely.','Count brave decisions—not results.','CORE RULE','Know your pitch.','Make the decision.','Take your swing.','SEE • DECIDE • COMMIT'],
['CHAPTER 8','THE STORY — PART 1','TEN BRAVE SWINGS','Earlier, Gio learned that swinging can be a victory','when he recognizes his pitch and commits.','','Now Coach Mark gives him another challenge:','10 Brave Swings.','','This is not a challenge to get 10 hits.','It is not a challenge to hit 10 home runs.','It is not even about making contact 10 times.','','The challenge is to make 10 good decisions','and fully commit to them.','','Committed swings feel different. No last-second','hesitation. No half-swing because he is afraid to miss.','TEN','SWINGS.','!','A BRAVE SWING STARTS WITH A GOOD DECISION.','SEE YOUR PITCH. TRUST YOUR CHOICE.','KNOW YOUR PITCH.','COMMIT COMPLETELY'],
['CHAPTER 8','THE STORY — PART 2','COLLECT THE EVIDENCE','Gio starts collecting Brave Swings.','','Some produce hits. Some produce foul balls.','Some miss. One becomes a hard line-drive out.','','Gio counts all of them when the decision','and commitment were good.','','Instead of asking, “Did I get a hit?”','he asks, “Did I take my swing?”','','Ten Brave Swings become ten pieces of evidence:','Gio can make a decision. Gio can commit.','Gio can trust himself.','TAKE YOUR SWING.','A committed decision counts—even when the result changes.','COUNT COURAGE.','MY PITCH. MY SWING.'],
['CHAPTER 8','WHAT GIO LEARNED','COMMITTED SWINGS','1  DEFINE THE WIN FIRST','Before the at-bat, decide','what success looks like:','recognize and commit.','2  COMMIT COMPLETELY','Once Gio chooses to swing,','he trusts the decision','instead of protecting from a miss.','3  TRACK WHAT YOU CONTROL','Counting Brave Swings','trains Gio to notice courage','and good decisions—not statistics.','WHY IT MATTERS','Players grow more confident when they repeatedly prove','they are willing to compete. The Brave Swing Challenge','gives Gio evidence that he can make a decision,','commit completely, and trust himself.','REAL BASEBALL EXAMPLE','Hitters improve through committed repetitions. A player','who consistently attacks the right pitches has a useful','process even when individual swings do not produce','the desired result.','','COACH MARK SAYS','See your pitch.','Take your swing.','BRAVE HITTERS COUNT COURAGE.','COMMITMENT'],
['CHAPTER 8','PARENT DUGOUT','COUNT BRAVE SWINGS','Help count Brave Swings without making a new result statistic.','PRAISE','✓ Recognizing the right pitch','✓ Making a clear decision','✓ Committing completely','✓ Swinging while nervous','✓ Returning after a miss','ASK','“Did you recognize your pitch?”','','“Did you commit?”','','','“Which swing felt best?”','AVOID','Turning the challenge into','another statistic your player','can fail.','','The purpose is evidence','of courage and willingness','to compete.','','PARENT REMINDER','Count brave decisions—not hits, runs, or contact.','Celebrate the willingness to compete.','HELP YOUR PLAYER COLLECT EVIDENCE OF COURAGE.','COMMITMENT'],
['CHAPTER 8','REFLECTION TIME','THINK. WRITE. GROW.','Track committed decisions and learn what they prove.','1. What makes a swing brave?','2. Which Brave Swing made you proudest?','3. Did you commit when you felt nervous?','4. What happened after you missed?','5. What did your 10 swings prove to you?','REMEMBER','Know your pitch.','Make the decision.','Commit completely.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','COMMITMENT'],
['CHAPTER 8','KEY TAKEAWAYS','REMEMBER THIS','1','KNOW YOUR PITCH.','2','MAKE THE DECISION.','3','COMMIT COMPLETELY.','4','COUNT COURAGE.','5','MY PITCH. MY SWING.','TEN BRAVE SWINGS BECOME EVIDENCE','THAT YOU CAN DECIDE, COMMIT, AND TRUST YOURSELF.','TAKE YOUR SWING.','COMMITMENT']
]});
