export const chapter4=Object.freeze({chapter:4,title:'STRIKEOUT SUPERHEROES',source:'APPROVED_STORYLINE.md#CHAPTER-4',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 4','STRIKEOUT','SUPER','HEROES','Next pitch.','Mental toughness is not never failing.','It is returning your attention to what comes next.','CORE RULE','Feel it.','Learn one thing.','Let it go.','RECOVER • RESET • RETURN TO READY'],
['CHAPTER 4','THE STORY — PART 1','THE AT-BAT IS OVER','Gio has an at-bat he wants to forget.','He swings through strike three.','','Walking back, he keeps replaying the pitch.','“I should have hit that. Why did I swing at that?”','','The at-bat is over, but Gio is still playing it in his mind.','On defense, he thinks about the strikeout—not the next play.','','Coach Mark notices. Even excellent hitters strike out.','Great players do not avoid every failure. What matters','is how they respond and where they put their attention next.','','The previous pitch cannot be changed.','The next opportunity still belongs to Gio.','WHAT IS','NEXT?','!','GREAT PLAYERS FAIL, TOO.','THE DIFFERENCE IS WHAT THEY DO NEXT.','RETURN TO READY.','NEXT PITCH'],
['CHAPTER 4','THE STORY — PART 2','NEXT PITCH','Coach Mark gives Gio two simple words: “Next pitch.”','Gio does not have to pretend the strikeout did not happen.','','He can feel disappointed, learn something useful,','and then release it. After a miss: next pitch.','After a bad call, an error, or a strikeout: next pitch.','','Later, Gio gets another opportunity. He takes a breath.','He does not carry the old at-bat back into the box.','He looks toward the pitcher and returns to the present.','','“Next pitch. My pitch,” Gio tells himself.','The previous failure no longer steals this opportunity.','Gio is ready to compete again—right here, right now.','“NEXT PITCH. MY PITCH.”','Recovery protects the next opportunity.','RETURN TO READY.','FEEL IT, LEARN, RELEASE, COMPETE'],
['CHAPTER 4','WHAT GIO LEARNED','NEXT PITCH','1  STRIKEOUTS HAPPEN','Striking out does not make Gio','a bad hitter. Failure is part','of hitting and baseball.','2  FEEL, LEARN, RELEASE','Gio can feel disappointed,','learn one useful thing, and','then move forward.','3  RETURN TO THE PRESENT','The last pitch cannot change.','The next pitch is where Gio','can compete.','WHY IT MATTERS','When Gio carries mistakes with him, one bad moment can','become several. Learning to reset protects the next pitch,','the next play, and the next at-bat—and returns his focus','to what he can do now.','REAL BASEBALL EXAMPLE','Every elite hitter strikes out and feels frustration. Their','advantage is often recovering quickly enough that the','previous failure does not steal the next opportunity.','Recovery is a skill great players practice.','','COACH MARK SAYS','Next pitch.','Your pitch.','BRAVE HITTERS RETURN TO THE PRESENT.','NEXT PITCH'],
['CHAPTER 4','PARENT DUGOUT','PRAISE THE RECOVERY','Let disappointment be felt without making it a bigger event.','PRAISE','✓ Returning to ready','✓ Learning one useful thing','✓ Releasing a mistake','✓ Refocusing on the next play','✓ Recovering with courage','ASK','“What did you learn?”','','“How quickly did you return','to ready?”','','“What comes next?”','AVOID','Rushing to erase the','disappointment.','','Let the player feel it','without turning the mistake','into a larger event.','','','PARENT REMINDER','Use simple language: “That one is over.” “What did you learn?”','“What’s next?” “Next pitch.”','PRAISE HOW QUICKLY THEY RETURN TO READY.','NEXT PITCH'],
['CHAPTER 4','REFLECTION TIME','THINK. WRITE. GROW.','Notice how you responded after a difficult baseball moment.','1. What mistake was hard to let go?','2. What useful thing could you learn from it?','3. How quickly did you return to ready?','4. What does “Next Pitch” mean to you?','5. What physical action can help you reset?','REMEMBER','Feel it. Learn one thing.','Let it go. Return your','attention to the next pitch.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','NEXT PITCH'],
['CHAPTER 4','KEY TAKEAWAYS','REMEMBER THIS','1','FAILURE IS PART OF BASEBALL.','2','FEEL IT.','3','LEARN ONE THING.','4','LET IT GO.','5','NEXT PITCH. YOUR PITCH.','THE PREVIOUS PITCH CANNOT BE CHANGED.','THE NEXT PITCH IS YOUR OPPORTUNITY.','RETURN TO THE PRESENT.','NEXT PITCH']
]});
