// Copy is drawn from APPROVED_STORYLINE.md, Chapter 11; line breaks fit frozen slots.
export const chapter11=Object.freeze({chapter:11,title:'TRUST YOUR TRAINING',source:'APPROVED_STORYLINE.md#CHAPTER-11',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 11','TRUST','YOUR','TRAINING','Train with purpose. Play with freedom.','The work is already in you.','One simple cue can free your swing.','CORE RULE','Practice with purpose.','Simplify in games.','Trust your work.','DO THE WORK. THEN TRUST IT.'],
['CHAPTER 11','THE STORY — PART 1','TOO MANY THOUGHTS','Gio has been working hard.','Batting practice, drills, tracking pitches, timing, Brave Swings.','But during a game, Gio starts thinking','about all of it at once.','','Where are my hands? Did I load?','Am I stepping correctly?','Is my bat in the right place?','','The more Gio tries to consciously control','every piece of his swing, the less natural','the swing feels.','','Coach Mark explains the difference between','PRACTICE MODE and GAME MODE.','TRUST','YOUR WORK.','!','PRACTICE IS WHERE YOU LEARN.','GAMES ARE WHERE YOU COMPETE.','PLAY FREE.','TRUST'],
['CHAPTER 11','THE STORY — PART 2','PLAY FREE','Practice is where Gio works on skills.','Practice is where he makes adjustments.','Practice is where he thinks about mechanics.','','The game is where he trusts that work.','','Coach Mark tells him:','“You already did the work. Now let your body play.”','','At his next at-bat, Gio chooses one simple focus.','See the ball. That is it.','He lets everything else happen.','His swing feels free again.','Trust is what preparation is for.','SEE THE BALL.','One simple focus.','DO THE WORK. THEN TRUST IT.','TRUST'],
['CHAPTER 11','WHAT GIO LEARNED','TRUST YOUR TRAINING','1  PRACTICE WITH PURPOSE','Training is the place to learn,','experiment, adjust, and repeat.','','2  SIMPLIFY IN COMPETITION','During games, Gio reduces his thoughts','instead of trying to consciously control','every movement.','3  TRUST THE WORK','Repeated preparation gives Gio permission','to stop micromanaging himself','and compete.','WHY IT MATTERS','Overthinking can make familiar movements feel difficult.','Learning when to think and when to trust helps Gio','bring his practice ability into games.','','REAL BASEBALL EXAMPLE','Athletes use practice to build repeatable movement patterns.','During competition, too much mechanical thinking can','interfere with reaction and timing.','Simple external cues often help players compete more freely.','','COACH MARK SAYS','See the ball.','Play free.','TRAIN WITH PURPOSE. PLAY WITH FREEDOM.','TRUST'],
['CHAPTER 11','PARENT DUGOUT','LET THEM PLAY FREE','Be careful about giving mechanical instructions immediately before or during every at-bat.','PRAISE','✓ Preparation','✓ A simple focus','✓ Competing freely','✓ Trusting the work','✓ Returning to the plan','SAY','“Trust your work.”','“See the ball.”','“Play free.”','“You prepared for this.”','','','AVOID','Mechanical instructions','during every at-bat.','','There is a time for','instruction. There is also','a time to compete.','','','PARENT REMINDER','Help your player separate practice mode from game mode.','Training is for adjustments. Games are for trust.','DO THE WORK. THEN TRUST IT.','TRUST'],
['CHAPTER 11','REFLECTION TIME','THINK. WRITE. GROW.','Notice how you can trust the work you have done.','1. What do you think about when you overthink?','2. What does a free swing feel like?','3. What work have you already done?','4. What one simple cue helps you compete?','5. When should you work on mechanics, and when should you trust them?','REMEMBER','Practice with purpose.','Simplify in games.','Trust your work.','BRAVE HITTERS TRUST THEIR TRAINING.','TRUST'],
['CHAPTER 11','KEY TAKEAWAYS','REMEMBER THIS','1','PRACTICE WITH PURPOSE.','2','MAKE ADJUSTMENTS IN TRAINING.','3','SIMPLIFY IN GAMES.','4','TRUST YOUR WORK.','5','DO THE WORK. THEN TRUST IT.','TRAIN WITH PURPOSE. PLAY WITH FREEDOM.','YOU PREPARED FOR THIS. PLAY FREE.','SEE THE BALL.','TRUST']
]});
