export const chapter6=Object.freeze({chapter:6,title:'VOICE IN YOUR HEAD',source:'APPROVED_STORYLINE.md#CHAPTER-6',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 6','VOICE','IN YOUR','HEAD','Replace negative thoughts.','Talk to yourself like a good coach would.','Useful words help you compete.','CORE RULE','Notice the thought.','Replace it with words that help.','Coach yourself with confidence.','NOTICE • REPLACE • COMPETE'],
['CHAPTER 6','THE STORY — PART 1','THE LOUDEST OPPONENT','Gio discovers that sometimes the loudest opponent','is not standing on the pitcher’s mound.','It is the voice inside his own head.','','After a miss: “You can’t hit this guy.”','After falling behind: “You’re going to strike out.”','Before a hard pitcher: “He’s too good.”','','Coach Mark explains that thoughts shape what Gio notices,','how his body feels, and how confidently he competes.','','Negative thoughts can show up automatically.','Gio can notice them without accepting them as truth.','','He does not have to believe every thought that appears.','INNER','VOICE.','!','THOUGHTS CAN SHOW UP AUTOMATICALLY.','GIO CAN CHOOSE WHAT HELPS NEXT.','NOTICE THE VOICE.','REPLACE THE THOUGHT'],
['CHAPTER 6','THE STORY — PART 2','COACH YOURSELF','Coach Mark asks what Gio would say if','a teammate had just missed a pitch.','Gio would never say, “You’re terrible.','You’re going to fail.”','He would say, “You’re good. Stay ready.','You’ve got the next one.”','“Then why wouldn’t you coach yourself the same way?”','Gio starts replacing negative thoughts with useful cues.','“I can’t hit him” becomes “See the ball.”','“Don’t strike out” becomes “Trust my swing.”','“I messed up” becomes “Next pitch.”','','His thoughts do not need to predict success.','They need to help him compete.','COACH YOURSELF THE SAME WAY.','Useful words point your attention toward the next action.','CHANGE THE MESSAGE.','USE WORDS THAT HELP YOU COMPETE'],
['CHAPTER 6','WHAT GIO LEARNED','USEFUL SELF-TALK','1  NOTICE THE VOICE','Negative thoughts can appear','without warning. First,','recognize what you hear.','2  DON’T ARGUE—REPLACE','Do not wrestle with the thought.','Swap it for a short instruction','that helps you compete.','3  BE YOUR OWN COACH','Use the same confidence and','patience you would give','a teammate.','WHY IT MATTERS','Thoughts shape attention and confidence. Useful self-talk','keeps Gio focused on actions instead of predictions','about failure. A short coaching cue gives his mind','something useful to do.','REAL BASEBALL EXAMPLE','Players often use short performance cues instead of long','internal speeches. “See it,” “stay ready,” or “next pitch”','direct attention toward the present moment and the','next controllable action.','','COACH MARK SAYS','Talk to yourself','like a good coach.','BRAVE HITTERS USE WORDS THAT HELP.','SELF-TALK'],
['CHAPTER 6','PARENT DUGOUT','LISTEN TO SELF-TALK','Help your player replace negative thoughts with useful cues.','PRAISE','✓ Noticing the thought','✓ Choosing a useful cue','✓ Calm recovery language','✓ Speaking like a teammate','✓ Returning to the next pitch','ASK','“What would Coach Mark say?”','','“What would you say to','your teammate?”','','“What phrase helps next?”','AVOID','Saying “Don’t say that!”','without helping your player','replace the thought.','','Negative self-talk needs a','useful next message.','','','PARENT REMINDER','Model calm language: “See the ball.” “Stay ready.”','“Trust your swing.” “Next pitch.”','HELP YOUR PLAYER BUILD USEFUL SELF-TALK.','SELF-TALK'],
['CHAPTER 6','REFLECTION TIME','THINK. WRITE. GROW.','Replace negative thoughts with words that help you compete.','1. What negative thought shows up most often?','2. What could you replace it with?','3. What would you tell a teammate?','4. Which short phrase helps you compete?','5. How does strong self-talk make your body feel?','REMEMBER','Notice the thought.','Replace the thought.','Be your own coach.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','SELF-TALK'],
['CHAPTER 6','KEY TAKEAWAYS','REMEMBER THIS','1','NOTICE THE THOUGHT.','2','REPLACE THE THOUGHT.','3','USE WORDS THAT HELP YOU COMPETE.','4','BE YOUR OWN GOOD COACH.','5','CHANGE THE MESSAGE. CHANGE THE MOMENT.','TALK TO YOURSELF WITH CONFIDENCE','AND GIVE YOUR MIND A USEFUL JOB.','COACH YOURSELF.','SELF-TALK']
]});
