import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument } from 'pdf-lib';
import { CHAPTER_FAMILIES, FONT, PAGE } from './production-config.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));const root=path.resolve(here,'../../..'),base=path.join(root,'production/pages/chapter-02'),sourceDir=path.join(base,'source'),pngDir=path.join(base,'png'),pdfPath=path.join(base,'pdf/brave-hitter-academy-chapter-02.pdf');
const failures=[],results=[];const check=(ok,label)=>{results.push({label,status:ok?'PASS':'FAIL'});if(!ok)failures.push(label);};const dims=b=>[b.readUInt32BE(16),b.readUInt32BE(20)];
const manifest=JSON.parse(fs.readFileSync(path.join(sourceDir,'build-manifest.json'),'utf8'));check(manifest.chapter===2,'Manifest identifies Chapter 2');check(manifest.families.join('|')===CHAPTER_FAMILIES.join('|'),'Seven families are in locked order');check(Object.values(manifest.assets).every(v=>!/production\/staging/i.test(v)),'No staging dependencies');check(Object.values(manifest.assets).every(v=>fs.existsSync(path.join(root,v))),'Every declared asset exists');check(Object.values(FONT).filter(v=>typeof v==='string'&&/\.(?:ttf|otf|woff2?)$/i.test(v)).every(v=>fs.existsSync(path.join(root,v))),'Every locked font exists');
const required=['SWINGING','COUNT BRAVE SWINGS','TWENTY BRAVE SWINGS','GOOD HITTERS DECIDE','PRAISE THE DECISION','What was your bravest swing?','COUNT BRAVE SWINGS, NOT JUST HITS.'];const prohibited=[/CHAPTER 1/,/COURAGE COMES BEFORE CONFIDENCE/,/production\/staging/i,/Page \d+ of/i,/spiral|coil binding/i,/REDS|Cincinnati|MLB/i];const hashes=[];
for(let i=0;i<7;i++){const p=i+1,sPath=path.join(sourceDir,`chapter_2_page_${p}.svg`),nPath=path.join(pngDir,`chapter_2_page_${p}.png`);check(fs.existsSync(sPath),`Page ${p} SVG exists`);check(fs.existsSync(nPath),`Page ${p} PNG exists`);if(!fs.existsSync(sPath)||!fs.existsSync(nPath))continue;const s=fs.readFileSync(sPath,'utf8'),n=fs.readFileSync(nPath),markup=s.replace(/data:image\/png;base64,[A-Za-z0-9+/=]+/g,'data:image/png;base64,[stripped]');check(s.includes(`family:${CHAPTER_FAMILIES[i]}`),`Page ${p} family metadata is correct`);check(s.includes(required[i]),`Page ${p} has authoritative anchor`);check(prohibited.every(re=>!re.test(markup)),`Page ${p} has no prohibited text`);const [w,h]=dims(n);check(w===PAGE.widthPx&&h===PAGE.heightPx,`Page ${p} PNG is 3300 × 2550`);hashes.push({page:p,family:CHAPTER_FAMILIES[i],svgSha256:crypto.createHash('sha256').update(s).digest('hex'),pngSha256:crypto.createHash('sha256').update(n).digest('hex')});}
check(fs.existsSync(pdfPath),'Chapter 2 PDF exists');if(fs.existsSync(pdfPath)){const bytes=fs.readFileSync(pdfPath),pdf=await PDFDocument.load(bytes);check(pdf.getPageCount()===7,'PDF has seven pages');for(const [i,p] of pdf.getPages().entries()){const {width,height}=p.getSize();check(Math.abs(width-PAGE.widthPt)<.01&&Math.abs(height-PAGE.heightPt)<.01,`PDF page ${i+1} is 792 × 612 points`);}check(bytes.length>5_000_000,'PDF contains full-resolution imagery');}
const report={generatedAt:new Date().toISOString(),status:failures.length?'FAIL':'PASS',results,hashes,failures};fs.writeFileSync(path.join(base,'preflight.json'),`${JSON.stringify(report,null,2)}\n`);console.log(`${report.status}: ${results.length-failures.length}/${results.length} checks passed`);if(failures.length){for(const failure of failures)console.error(`FAIL: ${failure}`);process.exitCode=1;}
