export const chapter2 = Object.freeze({
  chapter: 2,
  title: 'SWINGING IS WINNING',
  source: 'APPROVED_STORYLINE.md#CHAPTER-2',
  pageFamilies: ['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],
  pageText: [
    ['CHAPTER 2','SWINGING','IS','WINNING','20 Brave Swings.','A good decision can be a win.','Commit to the pitch you believe you can hit.','CORE RULE','See your pitch.','Trust it.','Take your swing.','DECISION • COMMITMENT • COURAGE'],
    ['CHAPTER 2','THE STORY — PART 1','COUNT BRAVE SWINGS','Gio is getting braver, but sometimes he still waits too long.','He is afraid to swing and miss.','','A hittable pitch goes by. Then another.','Gio is searching for a pitch that feels impossible to miss.','','Coach Mark asks, “How will you become a better hitter','if you’re afraid to take your swing?”','','A Brave Hitter does not swing at everything.','But when Gio recognizes his pitch, he needs to attack it.','Coach Mark gives him a challenge: stop counting hits.','','Count Brave Swings instead.','A Brave Swing is a good decision made with commitment.','SEE YOUR','PITCH.','!','GOOD HITTERS MAKE DECISIONS.','BRAVE HITTERS COMMIT TO THEIR PITCH.','COUNT BRAVE SWINGS.','SWINGING IS WINNING'],
    ['CHAPTER 2','THE STORY — PART 2','TWENTY BRAVE SWINGS','Gio begins working toward 20 Brave Swings.','Each one is a committed swing at a pitch he can hit.','','He might hit it hard, foul it off, or miss.','The result does not change whether the decision was brave.','Gio begins counting: one, two, three.','','With each committed swing, missing becomes less scary.','He stops protecting himself from failure and starts competing.','By his twentieth Brave Swing, something has changed.','','Gio no longer asks only, “Did I get a hit?”','He also asks, “Did I see my pitch and take my swing?”','Good decisions give him something useful to build on.','“DID I SEE MY PITCH AND TAKE MY SWING?”','Committed competition matters—even when Gio misses.','TRUST YOUR DECISION.','COUNT BRAVE SWINGS, NOT JUST HITS'],
    ['CHAPTER 2','WHAT GIO LEARNED','SWINGING IS WINNING','1  GOOD HITTERS DECIDE','Waiting forever does not make','hitting easier. Recognize your','pitch and decide to attack it.','2  A MISS CAN BE PROGRESS','Missing does not mean the swing','was bad. The right pitch and a','committed decision still matter.','3  COUNT COURAGE','Count the times you trusted','yourself enough to take your','swing—not only your hits.','WHY IT MATTERS','Fear of missing can make a hitter passive. Counting Brave','Swings gives Gio something he can control and develops','the habit of competing instead of waiting for a pitch','that feels impossible to miss.','REAL BASEBALL EXAMPLE','Great hitters swing and miss, foul pitches off, and make','outs. Development requires swings. A hitter who sees','hittable pitches and attacks them has something useful','to learn from, repeat, and keep building on.','','COACH MARK SAYS','See your pitch.','Trust your swing.','BRAVE HITTERS MAKE COMMITTED DECISIONS.','SWINGING IS WINNING'],
    ['CHAPTER 2','PARENT DUGOUT','PRAISE THE DECISION','Reinforce commitment before discussing the result.','PRAISE','✓ Taking a good swing','✓ Attacking a hittable pitch','✓ Staying aggressive','✓ Recovering after a miss','✓ Trusting the decision','ASK','“What was your bravest swing?”','','“Which pitch did you choose','to attack?”','','“What did you learn?”','AVOID','Creating fear around','swinging and missing.','','The goal is not reckless','swinging. It is confident,','committed decision-making.','','','PARENT REMINDER','Praise the decision and commitment first. Help your player','count Brave Swings—not only hits, strikeouts, or averages.','PRAISE COMMITTED COMPETITION.','SWINGING IS WINNING'],
    ['CHAPTER 2','REFLECTION TIME','THINK. WRITE. GROW.','Notice the good decisions and committed swings you made.','1. What was your bravest swing?','2. Which pitch did you attack without hesitating?','3. How did you respond after a swing and miss?','4. What makes a swing good even without a hit?','5. How many Brave Swings can you collect?','REMEMBER','A miss can still be','progress. See your pitch,','trust it, and take your swing.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','SWINGING IS WINNING'],
    ['CHAPTER 2','KEY TAKEAWAYS','REMEMBER THIS','1','SEE YOUR PITCH.','2','TRUST IT.','3','TAKE YOUR SWING.','4','MISSES HELP HITTERS GROW.','5','COUNT BRAVE SWINGS, NOT JUST HITS.','A GOOD DECISION AND A COMMITTED SWING','ARE WINS YOU CAN CONTROL.','KEEP CHOOSING TO COMPETE.','SWINGING IS WINNING'],
  ],
});
