export const chapter9=Object.freeze({chapter:9,title:'PRESSURE IS A PRIVILEGE',source:'APPROVED_STORYLINE.md#CHAPTER-9',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 9','PRESSURE','IS A','PRIVILEGE','Use Your Routine.','Same player. Same routine.','Big moment. Same job.','CORE RULE','Breathe.','Use your routine.','Trust the player you already are.','SAME PLAYER • SAME ROUTINE'],
['CHAPTER 9','THE STORY — PART 1','THE BIG MOMENT','Late in a close game, Gio hears his name.','He is up. Runners are on base.','','The crowd gets louder. His teammates are watching.','The walk from the dugout to home plate feels different.','','Gio starts thinking: “This is a huge at-bat.”','His breathing changes. His body feels tight.','He tries to create the perfect outcome','before he has even seen a pitch.','','Coach Mark reminds him: “You don’t need','a special swing because it’s a big moment.”','','The moment is bigger—but Gio’s job is not.','SAME','PLAYER.','!','A BIG MOMENT DOES NOT NEED A SPECIAL SWING.','USE THE ROUTINE YOU ALREADY TRUST.','SAME GAME. SAME ROUTINE.','PRESSURE'],
['CHAPTER 9','THE STORY — PART 2','RETURN TO FAMILIAR','The game situation has changed. Gio’s job has not.','','He takes a breath. Looks at his bat.','Steps toward the box. Finds the pitcher.','','The same routine he practiced in ordinary at-bats','brings him back to something familiar.','','The pressure is still there.','Gio does not need to fight it.','','He accepts that the moment matters,','welcomes the opportunity,','and returns to his routine.','USE YOUR ROUTINE.','Same player. Same routine. Big moment.','WELCOME THE MOMENT.','PRESSURE'],
['CHAPTER 9','WHAT GIO LEARNED','ROUTINE UNDER PRESSURE','1  PRESSURE MEANS IT MATTERS','Feeling nervous in a big moment','does not mean something is wrong.','It means Gio cares.','2  ROUTINES CREATE FAMILIARITY','Gio uses the same routine','in the first inning','and the final inning.','3  DON’T BECOME A DIFFERENT PLAYER','Big moments do not require','a harder swing or more thinking.','Gio trusts the player he already is.','WHY IT MATTERS','Pressure can pull Gio toward outcomes','and consequences. His routine brings his attention','back to familiar actions he can control.','That helps him compete as himself.','REAL BASEBALL EXAMPLE','High-level players rely on routines because game','situations constantly change. A repeatable preparation','process creates familiarity even when the moment','feels unusually important.','','COACH MARK SAYS','Same game.','Same routine.','BRAVE HITTERS TRUST THE PLAYER THEY ALREADY ARE.','PRESSURE'],
['CHAPTER 9','PARENT DUGOUT','KEEP THE MOMENT NORMAL','Help pressure feel familiar—not bigger.','PRAISE','✓ Taking a steady breath','✓ Returning to the routine','✓ Trusting the same preparation','✓ Competing while nervous','✓ Welcoming the opportunity','ASK','“What is your routine?”','','“What helps you feel familiar?”','','','“How can you trust yourself?”','AVOID','Making the moment bigger','than it already feels.','','Instead of “This is huge!”','try “Same game.”','“Same routine.”','“Trust yourself.”','“Enjoy the opportunity.”','PARENT REMINDER','Normalize nerves instead of treating them as a problem.','The moment can matter without changing the player.','HELP YOUR PLAYER TRUST THE FAMILIAR.','PRESSURE'],
['CHAPTER 9','REFLECTION TIME','THINK. WRITE. GROW.','Use your routine when the moment feels important.','1. What situations feel like pressure to you?','2. What happens in your body?','3. What is your routine?','4. What part of the routine helps most?','5. How can pressure feel exciting—not scary?','REMEMBER','Breathe.','Use your routine.','Welcome the moment.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','PRESSURE'],
['CHAPTER 9','KEY TAKEAWAYS','REMEMBER THIS','1','PRESSURE MEANS OPPORTUNITY.','2','BREATHE.','3','USE YOUR ROUTINE.','4','DON’T CHANGE WHO YOU ARE.','5','WELCOME THE MOMENT.','THE SITUATION MAY CHANGE,','BUT YOUR ROUTINE AND YOUR JOB STAY FAMILIAR.','TRUST YOUR ROUTINE.','PRESSURE']
]});
