export const chapter5=Object.freeze({chapter:5,title:'SECRET OF LINE DRIVES',source:'APPROVED_STORYLINE.md#CHAPTER-5',pageFamilies:['chapter-cover','story-part-1','story-part-2','what-gio-learned','parent-dugout','reflection-time','key-takeaways'],pageText:[
['CHAPTER 5','SECRET','OF LINE','DRIVES','Hard contact.','Good process produces good baseball over time.','A great swing can still become an out.','CORE RULE','Hunt good pitches.','Take good swings.','Hit the ball hard.','PITCH • SWING • QUALITY CONTACT'],
['CHAPTER 5','THE STORY — PART 1','A GREAT SWING—AN OUT','Gio has a simple rule: a hit is good and an out is bad.','Then he has an at-bat where everything feels right.','','He sees his pitch and takes a confident swing. CRACK!','A hard line drive shoots toward the outfield.','','The left fielder catches it. Gio walks back frustrated.','“Another out,” he thinks. Coach Mark asks him a question:','','“If that ball landed two feet to the side, would it','suddenly become a better swing?” Gio thinks about it.','Of course not. The swing was already good.','','The defender changed the result—not the quality of contact.','Gio needs a better way to judge what he did.','HARD','CONTACT.','!','THE SCOREBOOK RECORDS THE RESULT.','A HITTER CAN STILL RECOGNIZE A GREAT SWING.','NOTICE THE QUALITY.','HUNT HARD CONTACT'],
['CHAPTER 5','THE STORY — PART 2','HUNT HARD CONTACT','Coach Mark explains that results include things hitters','cannot control. A perfect swing can become an out.','','A weakly hit ball can become a hit. Brave Hitters need','a better way to judge themselves: hunt hard contact.','Gio watches the pitch, his decision, and his commitment.','','He notices how well he strikes the baseball.','He still wants hits—of course he does.','But the box score no longer decides how every swing feels.','','A line-drive out can still make Gio smile.','He recognizes the feeling of a pitch seen clearly,','a committed swing, and a baseball struck hard.','“THAT SWING WAS ALREADY GOOD.”','Quality contact matters even when a defender catches it.','HUNT HARD CONTACT.','GOOD PROCESS PRODUCES GOOD BASEBALL'],
['CHAPTER 5','WHAT GIO LEARNED','HARD CONTACT','1  HARD CONTACT IS A WIN','See your pitch and hit it hard.','You have done your job—even','when a defender catches it.','2  RESULTS CAN LIE','Not every hit is a great swing.','Not every out is a bad swing.','The scorebook misses context.','3  GRADE THE PROCESS','Evaluate what you control:','your decision, your swing,','and the quality of contact.','WHY IT MATTERS','If Gio judges himself only by hits, confidence depends on','luck, defense, and things outside his control. Focusing on','hard contact keeps attention on repeatable decisions,','committed swings, and useful feedback.','REAL BASEBALL EXAMPLE','A bloop hit and a line-drive out look very different to a','hitting coach than in the scorebook. Over time, consistently','striking baseballs hard matters far more than whether one','specific ball happened to find open grass.','','COACH MARK SAYS','That swing was','already good.','BRAVE HITTERS RECOGNIZE QUALITY CONTACT.','HARD CONTACT'],
['CHAPTER 5','PARENT DUGOUT','NOTICE HARD CONTACT','Teach your player to recognize quality beyond the result.','PRAISE','✓ A hard-hit baseball','✓ A good pitch decision','✓ A committed swing','✓ Quality contact on an out','✓ Repeating a strong process','ASK','“What did you hit hardest?”','','“Which swing felt best','today?”','','“What did you control?”','AVOID','Calling a great swing a','failure because a defender','caught the baseball.','','The result does not erase','the quality of contact.','','','PARENT REMINDER','Say: “You smoked that ball.” “Great swing.” “That was a','good pitch to hit.” “Keep doing that.”','HELP YOUR PLAYER RECOGNIZE QUALITY.','HARD CONTACT'],
['CHAPTER 5','REFLECTION TIME','THINK. WRITE. GROW.','Notice the quality of your contact—not only the box score.','1. What was your hardest-hit baseball?','2. Was an out still a great swing?','3. What makes contact good?','4. What parts of an at-bat can you control?','5. What changes if you track hard contact?','REMEMBER','A line-drive out can','still be a great swing.','Hunt hard contact.','BRAVE HITTERS REFLECT SO THEY CAN GROW.','HARD CONTACT'],
['CHAPTER 5','KEY TAKEAWAYS','REMEMBER THIS','1','HUNT GOOD PITCHES.','2','TAKE GOOD SWINGS.','3','HIT THE BALL HARD.','4','DO NOT LET THE SCOREBOOK DEFINE THE SWING.','5','HUNT HARD CONTACT.','GOOD PROCESS PRODUCES GOOD BASEBALL','OVER TIME—EVEN WHEN ONE SWING IS AN OUT.','RECOGNIZE QUALITY.','HARD CONTACT']
]});
